### ISSUE TITLE
Fix failure when there are other components than JavaScript

### ISSUE THREAD

**Issue by adelkahomolova** [DXHeroes/dx-scanner#103]
The scanning of the repository fails when there are other components than JavaScript.

![Screen Shot 2019-10-29 at 09 21 09](https://user-images.githubusercontent.com/53510747/67749463-81395000-fa2d-11e9-8a6c-150eec4a0502.png)

Use this repo to replicate error: https://github.com/sigalor/whatsapp-web-reveng.

There are two ways to fix this: 
1) Just log the message about error and let the scanner work on the JS repository.
2) Add necessary inspectors, component detectors and language detectors. See our Contribution Guide or other issues.

It would be great if you choose the first way of fixing first, as it will be fixed almost immediately.

**Comment by prokopsimek** [comment]
Now it works
