### ISSUE TITLE
Application won't start after clean install

### ISSUE THREAD

**Issue by PodlesnyJakub** [DXHeroes/dx-scanner#104]
Following the docs: 

1. I installed dx-scanner globaly with yarn.
2. I tried to run `dxscanner` even with `dxs` and `dx-scanner`
3. Everytime I recieved an error in bellow screenshot

![image](https://user-images.githubusercontent.com/38418381/67754836-666bd900-fa37-11e9-9caa-bfd50f920ddf.png)

**Comment by prokopsimek** [comment]
Related to https://github.com/streamich/memfs/issues/447 and https://github.com/streamich/memfs/issues/426.

Will lock the `memfs@2.15.5`.

**Comment by prokopsimek** [comment]
Should be fixed by https://github.com/DXHeroes/dx-scanner/pull/105 in new version `1.13.2` https://github.com/DXHeroes/dx-scanner/releases/tag/v1.13.2

All versions are now pinned and the new version `2.16.0` of `memfs` shouldn't be installed.

Could you retry it, please?

**Comment by prokopsimek** [comment]
@PodlesnyJakub 🙏

**Comment by prokopsimek** [comment]
Now it works
