### ISSUE TITLE
Unexpected object: bitbucket.org

### ISSUE THREAD

**Issue by jansedlon** [DXHeroes/dx-scanner#153]
Tried to run dx-scanner on repository locally that is hosted on bitbucket and it's a private repo.

**Comment by HonzsSedlomn** [comment]
![image](https://user-images.githubusercontent.com/13948180/68993328-0b2f4880-0877-11ea-8d9a-609265dae5dc.png)

**Comment by prokopsimek** [comment]
I have partially fixed the issue in version `1.17.9` (https://github.com/DXHeroes/dx-scanner/releases/tag/v1.17.9). It should be released after the pipeline (https://travis-ci.org/DXHeroes/dx-scanner/builds/612793921) finishes.

You can run the dx scanner with the URL in the form of:
```
dx-scanner https://username:appPassword@bitbucket.org/organization/repository
``` 
and it will require the authorization token twice.

---

It needs more work to be fixed totally.
- [ ] It's necessary to clone the remote repository with credentials. Now it doesn't work correctly.

**Comment by prokopsimek** [comment]
@jansedlon Hi Honza, it should work for now. Could you test it, please? Thanks! 🙂

**Comment by jansedlon** [comment]
@prokopsimek Hello Prokop, I'm so sorry for the delay. I've tried it with your command and it works like a charm, thank! :)
