### ISSUE TITLE
Cannot run dx-scanner from Windows

### ISSUE THREAD

**Issue by jansedlon** [DXHeroes/dx-scanner#155]
I've tried to run dx-scanner both from Windows Command Line and Windows Terminal (Preview).

Windows Command Line throws "The system cannot find the path specified".

Windows Terminal (Preview) throws: "The term /bin/sh.exe is not recognized as the name of cmdlet"
![image](https://user-images.githubusercontent.com/13948180/68995460-80f2de80-088e-11ea-9926-62600f9a6c42.png)

![image](https://user-images.githubusercontent.com/13948180/68995462-86e8bf80-088e-11ea-96f3-88ea1a5976be.png)

**Comment by prokopsimek** [comment]
@HonzsSedlomn Thanks for reporting the issue! 🙂We'll fix it soon as possible.

**Comment by prokopsimek** [comment]
@jansedlon Hi! PR #158 with a fix has been merged but there is another issue with installation on Windows #159 

Could you retry the new version on Windows?

**Comment by prokopsimek** [comment]
@jansedlon It seems to be fixed in #158 v1.17.10 (https://github.com/DXHeroes/dx-scanner/releases/tag/v1.17.10).

**Comment by prokopsimek** [comment]
It works for now
