### ISSUE TITLE
Scan for JavaScript dependencies with known security vulnerabilities

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/dx-scanner#179]

**Comment by prokopsimek** [comment]
Link to feature: https://dxheroes.productboard.com/feature-board/planning/features/2736434

**Comment by prokopsimek** [comment]
@adelkahomolova Please, add a detailed description for @vlasy.

**Comment by adelkahomolova** [comment]
Add new practice for checking if any security vulnerabilities are present. Check contribution guide to better orienting in the code, especially the practices. (https://github.com/DXHeroes/dx-scanner/blob/master/CONTRIBUTING.md#practices)

The practice should do the same thing as, e.g., https://snyk.io/ does. Let us know if you need some help.

@vlasy
