### ISSUE TITLE
[BUG] --ci mode doesn't throw an error if inserted wrong credentials

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/dx-scanner#260]
If the authorization argument contains invalid credentials and the command is run in on CI (`--ci`) so the command silently fails.

## Expected Behavior

It will throw an error that credentials are invalid.

## Current Behavior

```
08:33 $ yarn start run --ci -r -a asdf
yarn run v1.22.0
$ ./bin/run run --ci -r -a asdf
WARNING: You're running DX Scanner in development mode.
Scanning URI: /Users/prokop/Sites/_dxheroes/scanner... done
Scan duration 0s.
✨  Done in 20.76s.
```

## Possible Solution

It's probably catched by try/catch around `evaluate` function in the body of `Scanner.ts`. It's necessary to throw an error while running in `--ci` mode.

## Steps to Reproduce (for bugs)

1. run `yarn start run --ci -r -a asdf` on the DX Scanner source code

## Your Environment

* Version used: 2.10.1
* Environment name and version (e.g. Node 8): Node 12
* Operating System and version: MacOS
* Link to your project: https://github.com/DXHeroes/dx-scanner 🤣

**Comment by ryzzaki** [comment]
This issue has been merged in PR #279
