### ISSUE TITLE
[BUG] Listing issues fails on Bitbucket if issue tracker is not enabled

### ISSUE THREAD

**Issue by adelkahomolova** [DXHeroes/dx-scanner#263]
## Expected Behavior
Practice Solve Issue Continuously should return practicing as there are no issues if there is no issue tracker.

## Current Behavior
Practice Solve Issues Continuously fails if there is no issue tracker

## Possible Solution
Is there is no issue tracker return practicing instead of failing the practice.

## Steps to Reproduce (for bugs)

1. dxs run https://bitbucket.org/maras333/node-api-with-ts

**Comment by jnv** [comment]
I thought about this some more. In GitLab you can also disable issue tracker. So how about adding a method for checking whether issue tracking is available into `IIssueTrackingInspector`, say, `hasIssueTracker` and run that in the practice's method `isApplicable`?

**Comment by adelkahomolova** [comment]
Hi @jnv , thank you for your interest in contributing to our repository!
The problem is in Bitbucket response. The `listIssues` method in `BitbucketService` returns 404, so we have to check it in the service. My proposal is to wrap the [axios call on line 289](https://github.com/DXHeroes/dx-scanner/blob/master/src/services/bitbucket/BitbucketService.ts#L289)in try catch and check whether the message is `Repository has no issue tracker.` or not (see the picture).
<img width="434" alt="Screenshot 2020-10-15 at 12 24 50" src="https://user-images.githubusercontent.com/53510747/96111395-6e8b8580-0ee1-11eb-8940-2e2a0e460f9d.png">

**Comment by jnv** [comment]
Thanks @adelkahomolova, I have prepared the fix in #458.
