### ISSUE TITLE
Incorrect usage of Promise.all

### ISSUE THREAD

**Issue by jozolam** [DXHeroes/dx-scanner#287]
## Expected Behavior
Promise.all should be used when multiple promises can be resolved concurrently.
## Current Behavior
Promise.all is being used only on a few places and mostly for resolving already resolved promises.
example: https://github.com/DXHeroes/dx-scanner/blob/1692ac0a565c6c419bfac0f0c3b4f5a06d72e8ba/src/inspectors/GitInspector.ts#L114

Correct usage of Promise.all can improve performance by concurrent execution of multiple promises. I think the best place where to start is refactoring of these methods  

- https://github.com/DXHeroes/dx-scanner/blob/704fb51957d3816f1fbb3d8a8d0efb6e1a4ad44e/src/services/FileSystemService.ts#L116
- https://github.com/DXHeroes/dx-scanner/blob/704fb51957d3816f1fbb3d8a8d0efb6e1a4ad44e/src/services/git/Git.ts#L96

 Because they seem to be core of whole project.

## Possible Solution
Information how to used Promise.all correctly can be found in this article
https://www.freecodecamp.org/news/promise-all-in-javascript-with-example-6c8c5aea3e32/

**Comment by prokopsimek** [comment]
Thanks for the catch! We'll fix it.

**Comment by king-11** [comment]
@prokopsimek can i start working on this issue ?

**Comment by prokopsimek** [comment]
@king-11 Sure! Go ahead! 😍

**Comment by king-11** [comment]
@prokopsimek I encountered two issues and want to know your perspective abt it
- flat traverse in both of the files have two promises that they are awaiting so shall I first fetch metadata for all using Promise.all and then proceed for processing further using another Promis.all or something else should be one

- also current test for Git.ts and FileSystemService.ts check if function stops at once if false is returned but running them Promise.all will as far as I can see have to update tests too it can instead catch is Promise reject returned false something like that instead.

**Comment by adelkahomolova** [comment]
> flat traverse in both of the files + FileInspector.ts have two promises that they are awaiting so shall I first fetch metadata for all using Promise.all and then proceed for processing further using another Promis.all or something else should be one

There should be just one Promise.all. You'll just replace for loop for Promise.all.

> also current test for Git.ts and FileSystemService.ts check if function stops at once if false is returned but running them by Promise.all will fail the test; as far as I can see we have to update tests too it can instead catch if Promise reject has returned false something like that instead.

Yes, you should update the tests :) 

Did I help you? :) @king-11

**Comment by king-11** [comment]
one promise .all i didn't get that part 😅 because i would even to use async await maybe then...

**Comment by adelkahomolova** [comment]
I think you can do it in the almost same way as it is made in [Git.ts](https://github.com/DXHeroes/dx-scanner/blob/1692ac0a565c6c419bfac0f0c3b4f5a06d72e8ba/src/inspectors/GitInspector.ts#L114)
You will have something like
```js
    Promise.all(
      dirContent.map(async (cnt) => {
        const absolutePath = nodePath.resolve(path, cnt);
        const metadata = await this.getMetadata(absolutePath);

        const lambdaResult = fn(metadata);
        if (lambdaResult === false) return false;

        if (metadata.type === MetadataType.dir) {
          await this.flatTraverse(metadata.path, fn);
        }
      }),
    );
```

But maybe I'm wrong, that's also possible 😂 
Let me know if it helps @king-11

**Comment by king-11** [comment]
@adelkahomolova I guess I was just thinking too much looks good to me thanks for your quick reply :) I will send in the PR today
