### ISSUE TITLE
New Practice: Changelog is present

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/dx-scanner#397]
## New Practice Proposal

A new practice that checks if the repository contains a Changelog file.

**Comment by daniloff200** [comment]
I heard about this tool sometime ago in Twitter, also, today I suddenly found it in Hacktoberfest projects list :)

Could this one be assigned to me?  Wanna try to work with such tools, and make some work

**Comment by prokopsimek** [comment]
@daniloff200 Of course! 🎉

**Comment by iamRishabh07** [comment]
Hi, @prokopsimek I would like to work on this issue.

**Comment by prokopsimek** [comment]
@iamRishabh07 I am sorry, I have promised the issue for @daniloff200. 🤝

**Comment by adelkahomolova** [comment]
Hi @daniloff200 , let me know if you'll need any guidance from us. We are here for you 😇

**Comment by daniloff200** [comment]
hey @adelkahomolova 
yeah, I'm going to finish my PR this week :)

**Comment by daniloff200** [comment]
Ah, unfortunately I have a big rush on my current project, also, with library,  which I maintain, and, could'n make this one
Unnasigned myself
Sorry for that :disappointed:

**Comment by adelkahomolova** [comment]
Ok, thank you for letting me know @daniloff200 Maybe another time! I appreciate your interest in DX Scanner.

**Comment by K-Kumar-01** [comment]
Hello @adelkahomolova  and @prokopsimek 
I wanted to know more about this issue a bit.
Does it involve writing some code to automatically detect if a changlod.md file is present.
I am able to understand that from the description. 
Please correct me if i am wrong as i would like to have this issue

**Comment by adelkahomolova** [comment]
Hi @K-Kumar-01 , thank you for your interest in contributing to our repository. 
Yes, you should check whether [CHANGELOG.md](https://github.com/DXHeroes/dx-scanner/blob/master/CHANGELOG.md) is present or not. You can get the inspiration in already existing practice for checking whether [README.md](https://github.com/DXHeroes/dx-scanner/blob/master/README.md) is present [ReadmeIsPresentPractice](https://github.com/DXHeroes/dx-scanner/blob/master/src/practices/LanguageIndependent/ReadmeIsPresentPractice.ts). Is it clearer now? :)

**Comment by K-Kumar-01** [comment]
Yes, i would like to work up on this issue and let you know if i have any more doubts. Thanks @adelkahomolova  for the help

**Comment by adelkahomolova** [comment]
Sure, let me know if you'll need any help :) @K-Kumar-01

**Comment by K-Kumar-01** [comment]
Hello @adelkahomolova . I made a PR but it had some checks failing. I wasn't able to understand that. Could you  please tell a more about this

**Comment by adelkahomolova** [comment]
It's just a GitHub API rate limit. We use GH REST API and as there is a lot of calls, sometimes it exceeds the rate limit which is quite small for unauthorized users. Nothing which could be your fault. :) @K-Kumar-01

**Comment by adelkahomolova** [comment]
Solves #462

**Comment by prokopsimek** [comment]
Done
