### ISSUE TITLE
New Practice: Gitignore practice for Ruby

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/dx-scanner#408]
## New Practice Proposal

Create a new practice that checks correctly set `.gitignore` for Ruby.

**Comment by avats-dev** [comment]
Hey @prokopsimek , I want to work on this. Can you guide me a bit how to resolve this? Thanks.

**Comment by adelkahomolova** [comment]
Hi, @avats-dev , 
you can get the inspiration in already existing practices for other languages, for example for JavaScript [JsGitignoreCorrectlySetPractice](https://github.com/DXHeroes/dx-scanner/blob/master/src/practices/JavaScript/JsGitignoreCorrectlySetPractice.ts). You just need to respect the specification of Ruby for `.gitignore`. Don't forget to write tests, please! 

Thank you for your interest. I'm looking forward to your PR.

**Comment by avats-dev** [comment]
Thanks, @adelkahomolova for the insights. Working on this..:rocket:

**Comment by DominikMilaniak** [comment]
**Hi again** @avats-dev! 🙂 

A few days have passed since our last contact, how is it going so far with the issue? Is anything not clear enough or do you need help with something else? I am in no way pushing you, you can take as much time as you need 🙂  Just wanted to get in touch to make sure everything is ok 👍

**Comment by king-11** [comment]
@DominikMilaniak although I am working on another issue that one is taking a bit of time I can get this done quickly as I have already done one similar if you can assign this to me

**Comment by adelkahomolova** [comment]
Sure. Thanks @king-11 . I'm really glad that you enjoy contributing to our repository! You're awesome!
