### ISSUE TITLE
New Practice: Gitignore practice for C#

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/dx-scanner#409]
## New Practice Proposal

Create a new practice that checks correctly set `.gitignore` for C#.

**Comment by king-11** [comment]
@prokopsimek can I start working on this issue.

**Comment by adelkahomolova** [comment]
@king-11 Sure, do you need any intro? :)

**Comment by king-11** [comment]
@adelkahomolova i haven't written any practices yet so yeah an intro will help :)

**Comment by adelkahomolova** [comment]
Sure :)
You can get the inspiration in already existing practices for other languages, for example for JavaScript [JsGitignoreCorrectlySetPractice](https://github.com/DXHeroes/dx-scanner/blob/master/src/practices/JavaScript/JsGitignoreCorrectlySetPractice.ts). You just need to respect the specification of C# for `.gitignore`.
You can see other practices in the practices folder :)

Is it clear now? Let me know if you'll need any other help! @king-11

**Comment by king-11** [comment]
@adelkahomolova sorry for the delay so I wanted to ask that I have to create a new folder for C# I guess so what shall it be named :sweat_smile:

**Comment by king-11** [comment]
@adelkahomolova  sorry for the delay, so I started working on it but the gitignore practice that I found are for VisualStuidoCode, not C# so shall I use them as its the default IDE I believe for C# users.

**Comment by adelkahomolova** [comment]
Closed because it was solved in #457
