### ISSUE TITLE
New Practice: Used Linter for Go lang

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/dx-scanner#415]
## New Practice Proposal

Create a new practice that checks if is used linter for Go lang.

**Comment by anishkargaonkar** [comment]
@prokopsimek I would like to take this up. If yes, some pointers on how to get started will be very helpful.

**Comment by adelkahomolova** [comment]
@anishkargaonkar Hi, you can get the inspiration in our already existing practice for JavaScript. For JS, we check, if the user uses ESLint. Get the inspiration here [JavaScript/ESLintUsedPractice.ts](https://github.com/DXHeroes/dx-scanner/blob/master/src/practices/JavaScript/ESLintUsedPractice.ts)
So for the GoLang, you should check the most used linter for GoLang.

**Comment by anishkargaonkar** [comment]
@adelkahomolova thanks, it helps. The most commonly used linter for Go is [golint](https://pkg.go.dev/golang.org/x/lint/golint). Let me know if I can proceed with golint.

**Comment by adelkahomolova** [comment]
I tried to google it and it seems that there is more than one widely used linter in Go lang. So you can check whether the user is using at least one of them. I found e.g. golangci-lint. You can start working on this practice :) @anishkargaonkar

**Comment by adelkahomolova** [comment]
@anishkargaonkar Hi, how are you going? Do you need any help? :)

**Comment by anishkargaonkar** [comment]
@adelkahomolova it's going good, working on go package inspector. Actually, I do, there are 2 dependency managers available for golang, [dep](https://github.com/golang/dep) and [go mod](https://blog.golang.org/using-go-modules) which generate `Gopkg.toml` & `go.mod` respectively. I did find a parser for `.toml` file [@iarna/toml](https://www.npmjs.com/package/@iarna/toml) but could not find parser for `.mod` file.
Any suggestions regarding the `.mod` parser? Also if you can check out [@iarna/toml](https://www.npmjs.com/package/@iarna/toml) package or suggest something better would help.

**Comment by adelkahomolova** [comment]
Hey, I'm really sorry but I've just merged `GoComponentDetector`, where one of the contributors implemented also `GoPackageInspector`. Sorry about that! Pull the master to get the newest version of dx-scanner, please. @anishkargaonkar

**Comment by anishkargaonkar** [comment]
Sure, no problem.
