### ISSUE TITLE
New Practice: Used Linter for Python

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/dx-scanner#420]
## New Practice Proposal

Create a new practice that checks if is used linter for Python.

**Comment by ramesht007** [comment]
hey @prokopsimek , can I work on this

**Comment by prokopsimek** [comment]
@ramesht007 Go for it! 👏

**Comment by ramesht007** [comment]
Hey, @prokopsimek can you give me an example what exactly do i have to create. Do I have to create a workflow for Python linter.
Thanks

**Comment by prokopsimek** [comment]
@ramesht007 There is the similar practice for JavaScript and its linter ESLint. You can follow the implementation and update it for Python (the code is still in TypeScript).

Used Linter for JavaScript Practice: https://github.com/DXHeroes/dx-scanner/blob/master/src/practices/JavaScript/ESLintUsedPractice.ts

Tests: https://github.com/DXHeroes/dx-scanner/blob/master/src/practices/JavaScript/ESLintUsedPractice.spec.ts

**Comment by ramesht007** [comment]
Thanks

**Comment by ramesht007** [comment]
Do i have to write the code in TypeScript

**Comment by prokopsimek** [comment]
@ramesht007 Sure, the project is whole in TypeScript. The app can find any other language but the source code is in TypeScript.

**Comment by ramesht007** [comment]
ok thanks

**Comment by adelkahomolova** [comment]
@ramesht007 Hi, how are you going? Do you need any help? :)

**Comment by ramesht007** [comment]
Hey, @adelkahomolova sorry, for the delay, I am still trying to figure out how to wrtie the code in type script. Do have any tutorial for the same.

**Comment by adelkahomolova** [comment]
I'll just copy the message from my colleague Prokop, who already sent you big hint. @ramesht007 :

> There is the similar practice for JavaScript and its linter ESLint. You can follow the implementation and update it for Python (the code is still in TypeScript).
> 
> Used Linter for JavaScript Practice: https://github.com/DXHeroes/dx-scanner/blob/master/src/practices/JavaScript/ESLintUsedPractice.ts
> 
> Tests: https://github.com/DXHeroes/dx-scanner/blob/master/src/practices/JavaScript/ESLintUsedPractice.spec.ts

As he said - is almost the same. You'll just find linter for Python used by most Python programmers. The code will be almost the same as for ESLint.

**Comment by adelkahomolova** [comment]
Hi @ramesht007 how is it going with this issue?

**Comment by adelkahomolova** [comment]
Hi, @ramesht007 are you working on this issue?

**Comment by ramesht007** [comment]
sorry, @adelkahomolova I will not be able to this
Thanks for waiting 
But I am very busy with some other stuff.

**Comment by adelkahomolova** [comment]
Ok, thanks for the message.

**Comment by king-11** [comment]
@adelkahomolova I can work on this issue

**Comment by adelkahomolova** [comment]
@king-11 Sure! Go for it :)
