### ISSUE TITLE
docs : add links of gitlab & bigbucket repo

### ISSUE THREAD

**Issue by mohitrakhade20** [DXHeroes/dx-scanner#428]
## New Feature Proposal

Add links of gitlab, bigbucket and github  repo 
**gitlab** link :  https://gitlab.com/ubon-refer/smart-refer-api
**bigbucket** link : https://bitbucket.org/maras333/node-api-with-ts
**github** link:  https://github.com/DXHeroes/dx-scanner

**Comment by mohitrakhade20** [comment]
Can I work on this ?
I would love to contribute...

**Comment by prokopsimek** [comment]
@mohitrakhade20 Hi! Thank you for your suggestion. May I ask you where you would like to add these links?

**Comment by mohitrakhade20** [comment]
> This is README.md file

### Which version control system can you use?

Sure you can use `GitHub`. You can also use `GitLab` and `Bitbucket` no matter if it is public or private repo!

examples:
```
dx-scanner run https://github.com/DXHeroes/dx-scanner

dx-scanner run https://gitlab.com/ubon-refer/smart-refer-api

dx-scanner run https://bitbucket.org/maras333/node-api-with-ts
```
---

In the second line, I want to add hyperlinks of `GitHub` , `GitLab` and `Bitbucket`

**Comment by prokopsimek** [comment]
@mohitrakhade20 I understand. Thank you for your proposal but it's not necessary to have these links navigating to repository details. We mention just examples and it's clear enough to understand how it works.

**Comment by mohitrakhade20** [comment]
No problem, I will find other way to contribute. Let me know if you can help me.

**Comment by prokopsimek** [comment]
@mohitrakhade20 If you're experienced with TypeScript, you can choose one of our issues there: https://github.com/DXHeroes/dx-scanner/issues

If you would like to participate in DX Knowledge Base so you can write an article in our second repository there: https://github.com/DXHeroes/knowledge-base-content/issues

Do not hesitate to contact me if you have any other questions. 👏❤️
