### ISSUE TITLE
[BUG] Check for CI with Github Actions

### ISSUE THREAD

**Issue by dantehemerson** [DXHeroes/dx-scanner#444]
I have my CI workflow configured with [Github Actions](https://github.com/features/actions)(Currently only **testing**, but I could add **deployment** and other processes), but I'm getting the  message of: `- Use Continuous Integration` 

## Expected Behavior

The message of `- Use Continuous Integration` should not be shown because Github Action is configured for my project.
## Current Behavior

I'm getting the next message:

![image](https://user-images.githubusercontent.com/18385321/95004230-19c94000-05ae-11eb-9863-17c7586c4aba.png)

## Possible Solution

I think here it doesn't check for GitHub Action files, that are normally inside the `workflow` folder.
https://github.com/DXHeroes/dx-scanner/blob/da6b55e706318037d275d423662383cef01401fa/src/practices/LanguageIndependent/CIUsedPractice.ts#L27-L28
So it needs to check for files inside that folder.

I would like to work on this 🙂 if you consider it's is a bug.

## Steps to Reproduce (for bugs)

1. Run `dx-scanner run https://github.com/dantehemerson/fons`
2. Look at `Improvements with highest impact > - Use Continuous Integration` section

## Your Environment

* Version used: dx-scanner@3.39.1
* Environment name and version (e.g. Node 8): v12.18.0
* Operating System and version: Ubuntu 20.04 focal
* Link to your project: https://github.com/dantehemerson/fons

**Comment by adelkahomolova** [comment]
Hi, @dantehemerson , thanks for the catch! Sure, it would be awesome if you'll work on it. Let me know if you'll need any help. :)
