### ISSUE TITLE
Create a language detector for Python (~100 new lines of code)

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/dx-scanner#58]
We'd like to measure the quality of apps written in Python.

There are "language detectors" to determine what language is on which path.

It's necessary to implement **PythonLanguageDetector** the same way as is [JavaScriptLanguageDetector](https://github.com/DXHeroes/dx-scanner/blob/master/src/detectors/JavaScript/JavaScriptLanguageDetector.ts) implemented. It's around 100 new lines of code including tests.

More info in [our Contribution guide](https://github.com/DXHeroes/dx-scanner/blob/master/CONTRIBUTING.md).

**Comment by radektheloner** [comment]
:heart_eyes:

**Comment by johnny243** [comment]
Working on this issue :100:

**Comment by prokopsimek** [comment]
PR merged
