### ISSUE TITLE
Create a component detector for Python (~60 new lines of code)

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/dx-scanner#66]
We'd like to measure the quality of apps written in Python.

There are "component detectors" to determine frameworks, platform, and type of an application.

It's necessary to implement **PythonComponentDetector** the similar way as is [JavaComponentDetector](https://github.com/DXHeroes/dx-scanner/pull/50/files#diff-713f3c9ac097761276975cddf91b94b1) implemented. Because Python is not a front-end language, so it's not necessary to recognize Frontend/Backend platform. 
It's around 60 new lines of code including tests.

More info in [our Contribution guide](https://github.com/DXHeroes/dx-scanner/blob/master/CONTRIBUTING.md).

Other sources:
- [JavaComponentDetector](https://github.com/DXHeroes/dx-scanner/pull/50/files#diff-713f3c9ac097761276975cddf91b94b1)
- [JavaScriptComponentDetector (including FE&BE platform recognition)](https://github.com/DXHeroes/dx-scanner/blob/master/src/detectors/JavaScript/JavaScriptComponentDetector.ts)

**Comment by ryzzaki** [comment]
This issue has been solved & merged in PR #209
