### ISSUE TITLE
Create a component detector for Ruby (~60 new lines of code)

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/dx-scanner#68]
We'd like to measure the quality of apps written in Ruby.

There are "component detectors" to determine frameworks, platform, and type of an application.

It's necessary to implement **RubyComponentDetector** the similar way as is [JavaComponentDetector](https://github.com/DXHeroes/dx-scanner/pull/50/files#diff-713f3c9ac097761276975cddf91b94b1) implemented.
It's around 60 new lines of code including tests.

More info in [our Contribution guide](https://github.com/DXHeroes/dx-scanner/blob/master/CONTRIBUTING.md).

Other sources:
- [JavaComponentDetector](https://github.com/DXHeroes/dx-scanner/pull/50/files#diff-713f3c9ac097761276975cddf91b94b1)
- [JavaScriptComponentDetector (including FE&BE platform recognition)](https://github.com/DXHeroes/dx-scanner/blob/master/src/detectors/JavaScript/JavaScriptComponentDetector.ts)

**Comment by PuZZleDucK** [comment]
I've got a question about how dx-scanner would interpret some of the nuance of Gemfile versioning. Here are some examples from the Gemfile of another project:
```
gem "after_party"
gem "pg", ">= 0.18", "< 2.0"
```

There are 3 components here I'd like to ask questions about 🤔:

1. The 1st line of the example represents all that a Gemfile usually specifies and no version number is included... The other package inspectors seem to drop packages with no valid version specified, but for a Gemfile this would drop almost all of the packages. dx-scanner also seems to insist on completely specified semantic version. Would it be ok to add a package with the version '0.0.0' if it's version is not known from the Gemfile? or is there a more canonical way to signal this?

2. In the 2nd example `">= 0.18"` brings up similar questions, sometimes we only specify two of the three semantic version numbers. Should I just read this as '0.18.0'?

3. Then the final big question relates to the 2nd example: `">= 0.18", "< 2.0"`. Here there are multiple restrictions on the versioning (and just for kicks neither is completely specified 😅). Is there a way to specify a range of versions? Or should I just pick the min/max/average/0.0.0/something-else?

**Comment by PuZZleDucK** [comment]
I've answered at least one of my questions by experimenting... The semantic version construct is more flexible than I thought and happily accepts versions like "2.0" and "0.18"... I'm still not sure what to do with the symbols like ">=" or when there are multiple version constraints tho?

**Comment by adelkahomolova** [comment]
Hi, firstly I'm really sorry for the long delay. I had a crazy week.
1. I'm not sure if it's the best idea to save it as `0.0.0`. I think there should emerge the practice, which would warn the user about packages which doesn't have versioning because it's a bad practice.
3. Since I think that the best practice always is to have as a new version as possible, I would neglect the older possible version a save the newest which is allowed in gemfile. So if there would be something like `">= 0.11", "=< 3.0"` I would save `3.0.0`. 

What do you think about it? @PuZZleDucK
