### ISSUE TITLE
Create generator to install DX Scanner to the user's app.

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/dx-scanner#69]
As a developer, I would like to install DX Scanner in my repository as fast as possible.

The CLI has a new argument (e.g. `--init`) which creates my [configuration file](https://github.com/DXHeroes/dx-scanner#configuration-%EF%B8%8F) for DX Scanner in current folder.

**Expected scenario:**
1. Opens the dx-scanner repository on Github
2. Reads the readme and wants to try
3. Installs DX Scanner with `npm install dx-scanner` or `npm -g install dx-scanner`
4. Runs `dx-scanner --init`
  - this creates the `.dxscannerrc` in current folder

**More sexy solution (question & proposal):** 
- Is it possible to have a `post-install` command which is triggered immediately after `npm install dx-scanner` or `npm -g install dx-scanner`?

**Comment by lielfr** [comment]
I'd like to work on that

**Comment by prokopsimek** [comment]
@lielfr It's yours :) Thanks!

**Comment by prokopsimek** [comment]
PR #72

**Comment by prokopsimek** [comment]
Merged #72
