### ISSUE TITLE
Add auto-update feature

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/dx-scanner#71]
_As a user of DX Scanner, I'd like to have always the newest version of DX Scanner to have always newest features and not to increase my expansive time on the update._

The DX Scanner is a CLI tool and we'd like to offer the newest version of DX Scanner without his/her involvement always the DX Scanner is started.

**Comment by jnv** [comment]
IMO autoupdating is pretty disruptive, delays initial start and can cause troubles for the user. For example I want to stay on the older version of the package so I can compare results of scans across the longer period of time, or newer version causes troubles for me or breaks compatibility with my old version of Node etc.

The best practice I saw is to notify user about new version availability before the script exits, see [update-notifier](https://www.npmjs.com/package/update-notifier) – would you consider that instead?

**Comment by jnv** [comment]
Ah, I see there's #70, sorry.

**Comment by prokopsimek** [comment]
@jnv Hi, thanks for your valuable input. You're absolutely true but it would be fine at least to offer the update to the user. What do you think just to offer the update like programmatically instead of just a update warning?

**Comment by jnv** [comment]
> @prokopsimek What do you think just to offer the update like programmatically instead of just an update warning?

I am not sure what do you mean by that. Do you mean e.g. to prompt user for update or add some flag to allow automatic update, or provide an API?

**Comment by prokopsimek** [comment]
> > @prokopsimek What do you think just to offer the update like programmatically instead of just an update warning?
> 
> I am not sure what do you mean by that. Do you mean e.g. to prompt user for update or add some flag to allow automatic update, or provide an API?

I mean a prompt. Check if the new version exists and if yes, let's prompt the user with `Do you want update right now? (y/n)`

**Comment by jnv** [comment]
Yes, adding a prompt seems definitely like a more sensitive option, though I would still be wary of this rather non-standard behavior. I think there's a risk of introducing more complexity, e.g. then you will need an option to suppress the prompt.

Where this behavior makes the most sense to me is if you decide to distribute the package with bundled Node (e.g. as a tarball or OS-specific installer), which is where oclif can [help you with autoupdating](https://oclif.io/docs/releasing.html#autoupdater).

**Comment by prokopsimek** [comment]
@jnv Thanks a lot! I'll be thinking about it. It makes sense.

**Comment by prokopsimek** [comment]
Duplicity to #147
