### ISSUE TITLE
Add HTMLReporter to open DX report in browser

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/dx-scanner#75]
_As a user, I want to show DX report to my CTO or colleague in the HTML format let he/she understands it and has an overview of the project._

There are two reporters - [CLIReporter](https://github.com/DXHeroes/dx-scanner/blob/master/src/reporters/CLIReporter.ts) and [JSONReporter](https://github.com/DXHeroes/dx-scanner/blob/master/src/reporters/JSONReporter.ts). We need to create 3rd HTMLReporter to be able to report in HTML format.

**Definition of done:**
- create HTMLReporter
- same structure as CLI Reporter
- save HTML Report as a file
- enable to configure HTML report format in CLI arguments

For more info read [our Contribution guide](https://github.com/DXHeroes/dx-scanner/blob/master/CONTRIBUTING.md).

**Comment by ryzzaki** [comment]
Solved & Merged in PR #253
