### ISSUE TITLE
Concerns about CC-BY-NC-SA-4.0 license

### ISSUE THREAD

**Issue by jnv** [DXHeroes/dx-scanner#78]
I have noticed this project uses Creative Commons Attribution Non-Commercial Share-Alike license, which raises some concerns about using this project in commercial settings.

CC-NC licenses are not considered Free or Open-Source and are [not even recommended](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software) for software by Creative Commons. For example I cannot build upon dx-scanner in a project licensed under generally accepted license like MIT or GPL.

To nitpick upon that, your README file states:

> The DX Scanner open source project is licensed under the Attribution-NonCommercial-ShareAlike 4.0 International License.

Which is a contradiction, since the license is not compatible with open source. It is at best _source-available_ project.

A bigger concern is ambiguousness of this license when used for software. Some questions coming to my mind in particular:

- **What constitutes commercial use?**
  - Is it when I use the license in commercial project? How do you define one?
  - Is open-source project deemed commercial when I am paid for it (e.g. by client or through donations)?
  - Or you just don't want me to sell dx-scanner?
- **What is meant by Share Alike?**
  - When I change the code of the project for my personal purposes, do I need to share these changes publicly?
  - What if these changes are made inside a (commercial) organization, not distributed to clients but used for development of commercial software?
- **Who actually holds the copyright to the project?**
  - This is important because by default the contributors hold the copyright to their contributions. Should you decide to use the project commercially, you'd need an approval from all the contributors (as mentioned in [GNU's comment on CC-NC license](https://www.gnu.org/licenses/license-list#CC-BY-NC))  – unless they, say, waive their rights via CLA.

Personally, I'd like to recommend dx-scanner to be used in our organization along with other internal auditing tools, but I don't want to because of this license.

I understand there was some business decision to pick a non-FLOSS license for the project (for example to sell services along with this tool), but I recommend to reconsider or refine this approach. You can for example check some alternative software licenses like [License Zero](https://licensezero.com/) or [Blue Oak Model License](https://blueoakcouncil.org/license/1.0.0) or dual-license the project. Alternatively you should provide a FAQ which explains what is and what isn't acceptable usage under the license.

You should also consider a requirement for contributors to sign a CLA to enable you to actually use the project commercially and to relicense the project in the future.

A lot of these complexities would go away if you picked an appropriate software license. If commercial use or competition is your concern, pick viral license like (A)GPL to force others to share their modifications.

**Comment by prokopsimek** [comment]
@jnv Thanks for your explanation. I'll discuss it with my colleagues and I believe we change the license.

**Comment by prokopsimek** [comment]
@jnv We've changed the license to MIT. Thanks for your issue. :)
