### ISSUE TITLE
Create a language detector for .NET lang (~100 new lines of code)

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/dx-scanner#83]
We'd like to measure the quality of apps written in .NET.

There are "language detectors" to determine what language is on which path.

It's necessary to implement **DotNetLanguageDetector** the same way as is [JavaScriptLanguageDetector](https://github.com/DXHeroes/dx-scanner/blob/master/src/detectors/JavaScript/JavaScriptLanguageDetector.ts) implemented. It's around 100 new lines of code including tests.

More info in [our Contribution guide](https://github.com/DXHeroes/dx-scanner/blob/master/CONTRIBUTING.md).

**Comment by skneko** [comment]
I'm picking this up, but I think you perhaps want to split ".NET language" into 3 subcategories: C#, F# and Visual Basic.

**Comment by prokopsimek** [comment]
@skneko Huh, my bad. I have never worked in those languages and I don't know .NET fw. There already exists #60 to detect C# language but there is #65 to detect component correctly.

I wouldn't create F# or Visual Basic for now.
